base:
  env: test

test:
  base_url: "https://www.saucedemo.com/"
  timeout: 30000
  navigation_timeout: 60000
  headless: false
  browser: chromium
  credentials:
    username: standard_user
    password: secret_sauce

stage:
  base_url: "https://staging.saucedemo.com/"
  timeout: 30000
  navigation_timeout: 60000
  headless: false
  browser: chromium
  credentials:
    username: staging_user
    password: staging_password

prod:
  base_url: "https://www.saucedemo.com/"
  timeout: 30000
  navigation_timeout: 60000
  headless: true
  browser: chromium
  credentials:
    username: prod_user
    password: prod_password