name: CI

on:
  push:
    branches:
      - main
      - feature/**

  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  playwright-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - chromium
          - firefox
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Cache Playwright Browser
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{runner.os}}-${{ hashFiles('requirements.txt') }}
          restore-keys: playwright-${{runner.os}}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install Playwright Browser
        run: playwright install --with-deps

      - name: Install Allure commandline
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz
          tar -zxvf allure-2.34.1.tgz
          sudo mv allure-2.34.1 /opt/allure
          sudo ln -sf /opt/allure/bin/allure /usr/local/bin/allure
          allure --version

      - name: Run Loginout Test
        env:
          HEADLESS: "true"
          TEST_USER: ${{ secrets.TEST_USER }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          BROWSER: ${{ matrix.browser }}
        run: |
          pytest TestCase/test_login_out.py -v -s

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results -o allure-report --clean
      
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.browser }}
          path: allure-report
        
        
      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            allure-results
            screenshots
            logs
