name: CI

on:
  push:
    branches:
      - main
      - feature/**

  pull_request:
    branches:
      - main
# 自动取消并发运行
concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true


# 权限
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  playwright-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - chromium
          - firefox
    steps:
# 获取仓库检出代码
      - name: Checkout Code
        uses: actions/checkout@v4
# 设置 Python 环境
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: requirements.txt
# 缓存 Playwright 浏览器
      - name: Cache Playwright Browser
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{runner.os}}-${{ hashFiles('requirements.txt') }}
          restore-keys: playwright-${{runner.os}}-
# 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
# 安装 Playwright 浏览器
      - name: Install Playwright Browser
        run: playwright install 
# 运行测试-登录测试
      - name: Run Loginout Test
        env:
          HEADLESS: "true"
          TEST_USER: ${{ secrets.TEST_USER }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          BROWSER: ${{ matrix.browser }}
        run: |
          pytest TestCase/test_login_out.py -v -s
# 上传测试结果
      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.browser }}
          path: |
            allure-results
            screenshots
            logs
