name: Debug Allure Report

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  debug-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Show Workspace
        run: |
          echo "Current directory:"
          pwd

          echo ""
          echo "Repository files:"
          ls -la
