name: Debug Allure Report

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  debug-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Test Artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: ci.yml
          branch: ${{ github.ref_name }}
          workflow_conclusion: success
          path: artifacts

      - name: Show Downloaded Files
        run: |
          echo "Artifacts:"
          ls -R artifacts
