name: Deploy Allure Report

on:
  workflow_run:
    workflows: 
      - CI
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Test Artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: Show Downloaded Files
        run: |
          pwd
          ls -R artifacts

      - name: Merge Allure Results
        run: |
          mkdir -p merged-results
          find artifacts -type d -name "allure-results" | while read dir
          do
            echo "Processing: $dir"
            cp -r "$dir"/* merged-results/ || true
          done

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Allure Commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz

          tar -zxf allure-2.34.1.tgz

          sudo mv allure-2.34.1 /opt/allure

          sudo ln -sf /opt/allure/bin/allure /usr/local/bin/allure

          echo "Allure Version:"
          allure --version

      - name: Generate Allure Report
        run: |
          allure generate merged-results \
            -o allure-report \
            --clean

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

