name: Deploy Allure Report

on:
  workflow_run:
    workflows: 
      - CI
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Test Artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: Show Downloaded Files
        run: |
          pwd
          ls -R artifacts
