name: Deploy Allure Report

on:
  workflow_run:
    workflows: 
      - CI
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url}}
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Test Artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: Show Downloaded Files
        run: |
          pwd
          ls -R artifacts

      - name: Merge Allure Results
        run: |
          mkdir -p merged-results
          find artifacts -type d -name "allure-results" | while read dir
          do
            echo "Processing: $dir"
            cp -r "$dir"/* merged-results/ || true
          done

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Allure Commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz

          tar -zxf allure-2.34.1.tgz

          sudo mv allure-2.34.1 /opt/allure

          sudo ln -sf /opt/allure/bin/allure /usr/local/bin/allure

          echo "Allure Version:"
          allure --version

      - name: Generate Allure Report
        run: |
          allure generate merged-results \
            -o allure-report \
            --clean

      - name: Upload Pages Artifact
        continue-on-error: true
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Send Dynamic Message
        env:
          FEISHU_WEBHOOK: ${{secrets.FEISHU_WEBHOOK}}
          REPOSITORY: ${{github.repository}}
          BRANCH: ${{github.ref_name}}
          ACTOR: ${{github.actor}}
          WORKFLOW: ${{github.workflow}}
          COMMIT: ${{github.sha}}
          STATUS: success
          REPORT_URL: ${{ steps.deployment.outputs.page_url}}

        run: |
          MESSAGE=$(cat <<EOF
          🚀 Playwright 自动化测试完成
          📦 项目：$REPOSITORY
          🌿 分支：$BRANCH
          👤 提交人：$ACTOR
          ⚙ Workflow: $WORKFLOW
          ✅ 状态：$STATUS
          📝 Commit: ${COMMIT:0:7}
          🔗 测试报告：$REPORT_URL
          EOF
          )
          
          echo "$MESSAGE"

          JSON=$(jq -n \
            --arg text "$MESSAGE" \
            '{msg_type:"text",content:{text:$text}}')

          curl -X POST "$FEISHU_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "$JSON"       