name: First Workflow

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: python version
        run: python --version

      - name: SHow Files
        run: |
          pwd
          ls -la